### ISSUE TITLE
Adding internationalised validation messages

### ISSUE THREAD

**Issue by alexleonard** [ShawnMcCool/laravel-form-base-model#11]
Hey Shawn,

I've been puzzling over how to add internationalised messages to the form model.

I know I can create the $messages array in the form model, but I can't pull in Lang::line function results (PHP fundamentals at issue here).

```
public static $messages = array(
    'test_required' => 'This is a custom message that will render',
    'test2_required' => __('message.this_throws_a_php_error'),
);
```

So I thought I'd try handling it in the __construct using something like:

```
public function __construct() {
    $this->messages['test_required'] = __('messages.custom');
}
```

But this does nothing. This probably isn't an issue with the plugin itself but more a way of passing Lang returns to a static variable declared in a class.

Perhaps there's another way around it but I haven't found anything yet.

Any advice much appreciated!
Cheers,
Alex

**Comment by ShawnMcCool** [comment]
You can change the messages in the 'before_validation()' with static::messages['test_required'] = __('whatever');

$this->messages assigns to an instance variable in the class. 

The constructor never runs because the class is entirely based on static state. It'd be good if someone would modify this class to function as an object that is passed into the form view, instead of an object that is called statically, so that it can be unit-tested. But, I digress.

**Comment by alexleonard** [comment]
Awesome! Thanks so much for the advice Shawn. Sorry for my belated reply but Gmail's new auto-filing of emails pushed my notification out of sight (coupled with heavy workload).

I'll test that out today.

Cheers!
Alex
