### ISSUE TITLE
Laravel 4

### ISSUE THREAD

**Issue by Korri** [ShawnMcCool/laravel-form-base-model#12]
Is this project dead ? Is there any plan on migrating it to packagist ?

**Comment by ShawnMcCool** [comment]
I'll happily fix any bugs that come up. But, I'm accomplishing the goals that this bundle was designed to solve in completely different ways in Laravel 4. Once I have that all figured out, I'll probably release new packages.

**Comment by Korri** [comment]
Any chance to lean how you do that in Laravel 4 ? I'm looking for the lightest way to code a CRUD admin.

**Comment by ShawnMcCool** [comment]
In short I create a model object that contains the validation details for the model as well as any form specific logic. I instantiate that with IoC and then pass it into the view as $form.

I like to use a system on a number of applications before I release it. Otherwise, I don't really know what form I need it to take.

**Comment by Korri** [comment]
Hum, so something like [Ardent](https://github.com/laravelbook/ardent)  ? We currently use something like that on Codeigniter ([Datamapper ORM](http://datamapper.wanwizard.eu/)), but it sometimes feels like it links a Database model and it's forms to closely.

**Comment by ShawnMcCool** [comment]
No, I don't use Ardent. I create a class that exists to model a form rather than model an object in a database.
