### ISSUE TITLE
Save_input does not work correctly

### ISSUE THREAD

**Issue by krannich** [ShawnMcCool/laravel-form-base-model#6]
Hi,

we just figured out that there is an error in your save_input() method of line 193 when you pass an input parameter to this method.

It should be
static::set( $field_name, array_key_exists($field_name, $input) ? $input[$field_name] : '' );

since you refer to $input on line178 (but never use $input later on)
        if( is_null( $input ) )
            $input = Input::all();

Above line will fix this issue.

Can you please add this to this great bundle.
Thanks,
Dennis

**Comment by ShawnMcCool** [comment]
Thanks for finding that. I'll update it.

**Comment by krannich** [comment]
cool. and thanks for this great bundle.

**Comment by ShawnMcCool** [comment]
So, it turns out that you've touched on another issue. We can't do this:

static::set( $field_name, array_key_exists($field_name, $input) ? $input[$field_name] : '' );

Because it directly accesses $input[$field_name] which may not exist. So, I'm going to rework it to use Laravel's Fluent class as soon as I can.

**Comment by ShawnMcCool** [comment]
I have refactored the class and this should be correctly solved for.

**Comment by krannich** [comment]
cool, thanks a lot.
I'll give it a try in a minute.
all the best,
Dennis

Am 31.08.2012 um 23:41 schrieb Shawn McCool notifications@github.com:
